version: '3'
services:
  em.db:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: emapp
      POSTGRES_PASSWORD: empass
      POSTGRES_DB: emdb
      PGPASSWORD: empass
    volumes:
      - "em-db-data:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    networks:
      - emn
volumes:
  em-db-data:

networks:
  emn:
    driver: bridge
